---
- hosts: all
  become: true
  tasks:
     - name: Install Web server
       apt:
           name: apache2
           state: latest
	 - name: start Apache2
       service: 
            name: apache2
            state: started
